<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<test-results name="C:\Users\Gabriel\Desktop\TesteUnitarios\TesteRep\Win32\Debug\Project1.exe" total="3" errors="0" failures="1" ignored="0" inconclusive="0" not-run="0" skipped="0" invalid="0" date="2025-06-30" time="0.001">
  <culture-info current-culture="en" current-uiculture="en" />
  <test-suite type="Assembly" name="Project1.exe" executed="true" result="Failure" success="False" time="0.001" asserts="0">
    <results>
        <test-suite type="Namespace" name="Unit2" executed="true" result="Failure" success="False" time="0.000" asserts="0" >
          <results>
              <test-suite type="Fixture" name="TMyTestObject" executed="True" result="Failure" success="False" time="0.000" >
                <results>
                  <test-case name="Test1" executed="True" result="Failure" success="False" time="0.000" asserts="0" >
                    <failure>
                      <message>
                        <![CDATA[ Condition is False when True expected. [add está com erro] ]]>
                      </message>
                      <stack-trace>
                        <![CDATA[  ]]>
                      </stack-trace>
                    </failure>
                  </test-case>
                  <test-case name="Test2.TestA" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Test2.TestB" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                </results>
              </test-suite>
          </results>
        </test-suite>
    </results>
  </test-suite>
</test-results>
